#include "window_callback.h"
void createButtons(HWND window, HINSTANCE hInstance) {
    button1 = CreateWindowW(L"BUTTON", L"PLAY", WS_TABSTOP | WS_VISIBLE | WS_CHILD | BS_DEFPUSHBUTTON | BS_OWNERDRAW , 456, 568, 200, 50, window, (HMENU)IDC_BUTTON1, hInstance, NULL);
  
    button2 = CreateWindowW(L"BUTTON", L"EXIT GAME", WS_TABSTOP | WS_VISIBLE | WS_CHILD | BS_DEFPUSHBUTTON | BS_OWNERDRAW, 456, 668, 200, 50, window, (HMENU)IDC_BUTTON2, hInstance, NULL);

    button3 = CreateWindowW(L"BUTTON", L"RULES", WS_TABSTOP| WS_VISIBLE | WS_CHILD | BS_DEFPUSHBUTTON | BS_OWNERDRAW, 456, 768, 200, 50, window, (HMENU)IDC_BUTTON3, hInstance, NULL);

    button4 = CreateWindowW(L"BUTTON", L"Back to menu", WS_TABSTOP | WS_VISIBLE | WS_CHILD | BS_DEFPUSHBUTTON | BS_OWNERDRAW, 35, 35, 60, 30, window, (HMENU)IDC_BUTTON4, hInstance, NULL);

    button5 = CreateWindowW(L"BUTTON", L"WIZARD", WS_TABSTOP | WS_VISIBLE | WS_CHILD | BS_DEFPUSHBUTTON | BS_OWNERDRAW , 142, 230, 200, 230, window, (HMENU)IDC_BUTTON5, hInstance, NULL);

    button6 = CreateWindowW(L"BUTTON", L"KNIGHT", WS_TABSTOP | WS_VISIBLE | WS_CHILD | BS_DEFPUSHBUTTON | BS_OWNERDRAW, 448, 230, 200, 230, window, (HMENU)IDC_BUTTON6, hInstance, NULL);

    button7 = CreateWindowW(L"BUTTON", L"THIEF", WS_TABSTOP | WS_VISIBLE | WS_CHILD | BS_DEFPUSHBUTTON | BS_OWNERDRAW, 754, 230, 200, 230, window, (HMENU)IDC_BUTTON7, hInstance, NULL);

    button8 = CreateWindowW(L"BUTTON", L"VAMPIRE", WS_TABSTOP | WS_VISIBLE | WS_CHILD | BS_DEFPUSHBUTTON | BS_OWNERDRAW, 277, 500, 200, 230, window, (HMENU)IDC_BUTTON8, hInstance, NULL);

    button9 = CreateWindowW(L"BUTTON", L"ARCHER", WS_TABSTOP | WS_VISIBLE | WS_CHILD | BS_DEFPUSHBUTTON | BS_OWNERDRAW, 619, 500, 200, 230, window, (HMENU)IDC_BUTTON9, hInstance, NULL);

    button10 = CreateWindowW(L"BUTTON", L"Next --->", WS_TABSTOP | WS_VISIBLE | WS_CHILD | BS_DEFPUSHBUTTON | BS_OWNERDRAW, 905, 900, 150, 50, window, (HMENU)IDC_BUTTON10, hInstance, NULL);
}